# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /h/u16/c4/00/leepet20/personal/ring-all-reduce

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /h/u16/c4/00/leepet20/personal/ring-all-reduce

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /h/u16/c4/00/leepet20/personal/ring-all-reduce/CMakeFiles /h/u16/c4/00/leepet20/personal/ring-all-reduce//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /h/u16/c4/00/leepet20/personal/ring-all-reduce/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named train_local

# Build rule for target.
train_local: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 train_local
.PHONY : train_local

# fast build rule for target.
train_local/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/build
.PHONY : train_local/fast

src/dataset.o: src/dataset.cpp.o
.PHONY : src/dataset.o

# target to build an object file
src/dataset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/dataset.cpp.o
.PHONY : src/dataset.cpp.o

src/dataset.i: src/dataset.cpp.i
.PHONY : src/dataset.i

# target to preprocess a source file
src/dataset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/dataset.cpp.i
.PHONY : src/dataset.cpp.i

src/dataset.s: src/dataset.cpp.s
.PHONY : src/dataset.s

# target to generate assembly for a file
src/dataset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/dataset.cpp.s
.PHONY : src/dataset.cpp.s

src/shallow_nn.o: src/shallow_nn.cpp.o
.PHONY : src/shallow_nn.o

# target to build an object file
src/shallow_nn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/shallow_nn.cpp.o
.PHONY : src/shallow_nn.cpp.o

src/shallow_nn.i: src/shallow_nn.cpp.i
.PHONY : src/shallow_nn.i

# target to preprocess a source file
src/shallow_nn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/shallow_nn.cpp.i
.PHONY : src/shallow_nn.cpp.i

src/shallow_nn.s: src/shallow_nn.cpp.s
.PHONY : src/shallow_nn.s

# target to generate assembly for a file
src/shallow_nn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/shallow_nn.cpp.s
.PHONY : src/shallow_nn.cpp.s

src/train_main.o: src/train_main.cpp.o
.PHONY : src/train_main.o

# target to build an object file
src/train_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/train_main.cpp.o
.PHONY : src/train_main.cpp.o

src/train_main.i: src/train_main.cpp.i
.PHONY : src/train_main.i

# target to preprocess a source file
src/train_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/train_main.cpp.i
.PHONY : src/train_main.cpp.i

src/train_main.s: src/train_main.cpp.s
.PHONY : src/train_main.s

# target to generate assembly for a file
src/train_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_local.dir/build.make CMakeFiles/train_local.dir/src/train_main.cpp.s
.PHONY : src/train_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... train_local"
	@echo "... src/dataset.o"
	@echo "... src/dataset.i"
	@echo "... src/dataset.s"
	@echo "... src/shallow_nn.o"
	@echo "... src/shallow_nn.i"
	@echo "... src/shallow_nn.s"
	@echo "... src/train_main.o"
	@echo "... src/train_main.i"
	@echo "... src/train_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

